### ISSUE TITLE
请问这些坏味道是如何定义的呀？

### ISSUE THREAD

**Issue by Rabbitzzc** [twfe/lemonj#2]
如题

**Comment by phodal** [comment]
你对哪个不清楚呢？

**Comment by Rabbitzzc** [comment]
> 你对哪个不清楚呢？

![image](https://user-images.githubusercontent.com/26913511/100693776-8737f800-33c8-11eb-9598-ea3255d88304.png)
除了 `importants` ，其他的都比较好奇为何会定义为坏味道，之前看的一些书籍中没有提到过，所以想请教一下背景，谢谢。

**Comment by phodal** [comment]
这是的坏味道是基于数量的场景：

1. 奇数的宽度，会导致没办法居中。
2. 字体、absolute 过多，说明缺少规范
3. mediaQueries 过少，说明缺少响应式设计

要不来个 PR 说明一下？
